name: CI

on: 
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Jekyll Action
      uses: helaili/jekyll-action@1.0
